<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Donalds-MacBook-Pro.local" name="unhappyPath" tests="3" failures="1" timestamp="9 Oct 2017 18:52:56 GMT" time="59.038" errors="0">
  <testcase name="PhoneNumberValidation" time="6.154" classname="com.zopa.Tests.SignUp_SadPath">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at com.zopa.Tests.SignUp_SadPath.PhoneNumberValidation(SignUp_SadPath.java:47)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- PhoneNumberValidation -->
  <testcase name="PostCodeValidation" time="6.619" classname="com.zopa.Tests.SignUp_SadPath"/>
  <testcase name="emailVerification" time="10.533" classname="com.zopa.Tests.SignUp_SadPath"/>
</testsuite> <!-- unhappyPath -->
